services:
  web:
    build: .
    image: gym-be:latest
    container_name: gym-be-web
    environment:
      SMART_STORE_ENV: docker
      PYTHONPATH: /app
      SMART_STORE_DB_SERVER_URL: postgresql+psycopg2://postgres:postgres@db:5432/
      SMART_STORE_DB_NAME: gym_admin
      TZ: "America/Bogota"  # Corregido: con dos puntos y espacio
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always

  db:
    image: postgres:16
    container_name: gym-be-db
    # Agregamos este comando para que Postgres use la zona horaria internamente
    command: -c timezone='America/Bogota'
    environment:
      TZ: "America/Bogota" # Corregido
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gym_admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "55432:5432" 
    restart: always

volumes:
  pgdata: